---
name: proxrm CD

on:  # yamllint disable-line rule:truthy
  push:
    tags: ["v*.*.*"]

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes
permissions:
  actions: write
  contents: write

jobs:
  #
  # CD
  #
  evaluate:
    name: Evaluate proxrm
    uses: CTFfactory/golang-workflows/.github/workflows/evaluate.yml@main
  release:
    name: Build & Release proxrm
    needs: evaluate
    uses: CTFfactory/golang-workflows/.github/workflows/release.yml@main
    with:
      name: proxrm
    secrets: inherit
