---
name: proxrm CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ['*']

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes
permissions:
  contents: read

jobs:
  #
  # CI
  #
  evaluate:
    name: Evaluate proxrm
    uses: CTFfactory/golang-workflows/.github/workflows/evaluate.yml@main
  build:
    name: Build proxrm
    needs: evaluate
    uses: CTFfactory/golang-workflows/.github/workflows/build.yml@main
    secrets: inherit
